langauge: python
python:
  - "3.6"
  - "3.7"

cache:
  pip: true

before_install:
  - git submodule update --init
  - git lfs pull
  - pip install numpy cython --user
  - pip install n2 nose --user

install:
  - pip setup.py install --user
  - pip install -r requirements.txt --user

script:
  - cd tests && pytest -k "not ml_20m" -k "not text8"

notifications:
  email: false

virtualenv:
  system_site_packages: true
