langauge: python
python:
  - "3.6"
  - "3.7"

addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

cache:
  pip: true
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.6
      before_install:
        - pip3 install --upgrade pip --user
        - git submodule update --init
        - git lfs pull
        - pip3 install numpy cython --user
        - pip3 install n2 nose --user
        - python3 setup.py install
      after_install:
        - pip3 install -r requirements.txt --user

script:
  - cd tests && pytest -k "not ml_20m" -k "not text8"

notifications:
  email: false

virtualenv:
  system_site_packages: true
